//! Regular {p,q} tilings, generated by reflecting a base tile.

use crate::circle::Circle;
use crate::geometry2d::{self, Geometry};
use crate::mobius::{Mobius, Transform};
use crate::nethash::{NetMap, NetSet};
use crate::polygon::{Polygon, Segment};
use crate::tile::Tile;
use crate::vector3d::Vector3D;
use std::f64::consts::PI;

#[derive(Clone, Copy, Debug)]
pub struct TilingConfig {
    pub p: i32,
    pub q: i32,
    /// A Möbius transformation to apply while creating the tiling.
    pub m: Mobius,
    /// The max number of tiles to include.
    pub max_tiles: usize,
    /// A shrinkage applied to the drawn polygons (1.0 means none).
    pub shrink: f64,
}

impl TilingConfig {
    pub fn new(p: i32, q: i32, max_tiles: usize) -> TilingConfig {
        TilingConfig { p, q, m: Mobius::identity(), max_tiles, shrink: 1.0 }
    }

    /// A complete spherical tiling (a Platonic solid). Returns `None` if {p,q} isn't one.
    pub fn spherical(p: i32, q: i32) -> Option<TilingConfig> {
        geometry2d::num_platonic_facets(p, q).map(|n| TilingConfig::new(p, q, n as usize))
    }

    pub fn geometry(&self) -> Geometry {
        Geometry::from_pq(self.p, self.q)
    }

    /// A Möbius transformation centering the tiling on a vertex (useful for dual tilings).
    pub fn vertex_centered_mobius(&self) -> Mobius {
        vertex_centered_mobius(self.p, self.q)
    }

    /// A Möbius transformation centering the tiling on an edge.
    pub fn edge_mobius(&self) -> Mobius {
        let g = self.geometry();
        let mut poly = Polygon::default();
        poly.create_regular(self.p, self.q);
        let mut offset = poly.segments[0].midpoint();
        let angle = PI / self.p as f64;
        offset.rotate_xy(-angle);
        let mut m = Mobius::default();
        m.isometry(g, -angle, -offset);
        m
    }
}

pub fn vertex_centered_mobius(p: i32, q: i32) -> Mobius {
    let mut angle = PI / q as f64;
    if q % 2 == 0 {
        angle *= 2.0;
    }
    let mut offset = Vector3D::new(-geometry2d::normalized_circum_radius(p, q), 0.0);
    offset.rotate_xy(angle);
    let mut m = Mobius::default();
    m.isometry(Geometry::from_pq(p, q), angle, offset);
    m
}

/// Where the tiling is centered.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum Projection {
    #[default]
    FaceCentered,
    EdgeCentered,
    VertexCentered,
}

/// Just the tile center positions of a tiling, generated by reflecting in the fundamental
/// triangle's mirrors (much cheaper than a full tiling).
#[derive(Clone, Debug, Default)]
pub struct TilingPositions {
    pub positions: NetSet<Vector3D>,
}

impl TilingPositions {
    pub fn build(config: &TilingConfig) -> TilingPositions {
        let tile = Tiling::create_base_tile(config);

        // Fundamental triangle definition.
        let seg = tile.boundary.segments[0];
        let (p1, p2, p3) = (Vector3D::ORIGIN, seg.midpoint(), seg.p1);
        let mirrors = [Circle::from_2_points(p1, p2), Circle::from_2_points(p1, p3), seg.circle()];

        let mut positions = NetSet::new();
        let mut starting = vec![Vector3D::ORIGIN];
        let g = config.geometry();
        'levels: while !starting.is_empty() {
            let mut added = NetSet::new();
            for v in &starting {
                for c in &mirrors {
                    let candidate = c.reflect_point(*v);
                    // Same magic number as in Tile::include_after_mobius (roughly).
                    if g == Geometry::Hyperbolic && candidate.abs() > 0.9999 {
                        continue;
                    }

                    if positions.insert(candidate) {
                        added.insert(candidate);
                    }

                    if positions.len() + 1 > config.max_tiles {
                        break 'levels;
                    }
                }
            }
            starting = added.into_vec();
        }

        TilingPositions { positions }
    }
}

#[derive(Clone, Debug)]
pub struct Tiling {
    pub config: TilingConfig,
    pub tiles: Vec<Tile>,
    /// Tile centers to tile indices.
    pub tile_positions: NetMap<Vector3D, usize>,
    /// Edge midpoints to the tiles sharing that edge.
    pub edge_incidences: NetMap<Vector3D, Vec<usize>>,
    /// Vertices to the tiles sharing that vertex.
    pub vertex_incidences: NetMap<Vector3D, Vec<usize>>,
}

impl Tiling {
    pub fn generate(config: TilingConfig) -> Tiling {
        Tiling::generate_with_projection(config, Projection::FaceCentered)
    }

    pub fn generate_with_projection(config: TilingConfig, projection: Projection) -> Tiling {
        let mut tiling = Tiling {
            config,
            tiles: Vec::new(),
            tile_positions: NetMap::new(),
            edge_incidences: NetMap::new(),
            vertex_incidences: NetMap::new(),
        };

        let mut tile = Tiling::create_base_tile(&config);

        match projection {
            Projection::VertexCentered => tile.transform(&config.vertex_centered_mobius()),
            Projection::EdgeCentered => tile.transform(&config.edge_mobius()),
            Projection::FaceCentered => {}
        }

        tiling.transform_and_add(&tile);

        let mut completed = NetSet::new();
        completed.insert(tile.boundary.center);
        tiling.reflect_recursive(vec![tile.clone_geometry()], &mut completed);

        // Isometries taking each tile back to the home tile.
        let g = config.geometry();
        for t in &mut tiling.tiles {
            let boundary = t.boundary.clone();
            t.isometry.calculate_from_two_polygons(&tile, &boundary, g);
        }

        tiling.fill_out_incidences();
        tiling
    }

    pub fn create_base_tile(config: &TilingConfig) -> Tile {
        let mut boundary = Polygon::default();
        boundary.create_regular(config.p, config.q);
        let drawn = boundary.clone();
        let mut tile = Tile::new(boundary, drawn, config.geometry());
        tile.shrink(config.shrink);
        tile
    }

    /// Clones, transforms and adds a tile. Returns false if the tile shouldn't be included.
    fn transform_and_add(&mut self, tile: &Tile) -> bool {
        if !tile.include_after_mobius(&self.config.m) {
            return false;
        }

        let mut clone = tile.clone_geometry();
        clone.transform(&self.config.m);
        self.tile_positions.insert(clone.boundary.center, self.tiles.len());
        self.tiles.push(clone);
        true
    }

    /// Whether reflecting a tile in a segment gives a new tile. Cheaper than reflecting the tile.
    fn new_tile_after_reflect(&self, t: &Tile, s: &Segment, completed: &NetSet<Vector3D>) -> bool {
        let mut new_vertex_circle = t.vertex_circle.clone();
        new_vertex_circle.reflect_segment(s);
        let test_center = self.config.m.apply(new_vertex_circle.center_ne);
        !completed.contains(&test_center)
    }

    /// Breadth-first reflection.
    fn reflect_recursive(&mut self, mut tiles: Vec<Tile>, completed: &mut NetSet<Vector3D>) {
        while !tiles.is_empty() {
            let mut reflected = Vec::new();

            for tile in &tiles {
                // We don't reflect tiles living out at infinity. Strange things happen, and we
                // still get the full tiling without doing it.
                if tile.has_points_projected_to_infinity() {
                    continue;
                }

                if self.tiles.len() >= self.config.max_tiles {
                    return;
                }

                for seg in &tile.boundary.segments {
                    if !self.new_tile_after_reflect(tile, seg, completed) {
                        continue;
                    }

                    let mut new_base = tile.clone_geometry();
                    new_base.reflect(seg);
                    if self.transform_and_add(&new_base) {
                        completed.insert(new_base.boundary.center);
                        reflected.push(new_base);
                    }
                }
            }

            tiles = reflected;
        }
    }

    /// Fills out the edge and vertex incidence information.
    fn fill_out_incidences(&mut self) {
        let mut edges: NetMap<Vector3D, Vec<usize>> = NetMap::new();
        let mut vertices: NetMap<Vector3D, Vec<usize>> = NetMap::new();

        for (i, t) in self.tiles.iter().enumerate() {
            for edge in t.boundary.edge_midpoints() {
                edges.get_or_insert_with(edge, Vec::new).push(i);
            }
            for vertex in t.boundary.vertices() {
                vertices.get_or_insert_with(vertex, Vec::new).push(i);
            }
        }

        for list in edges.values() {
            for &t in list {
                self.tiles[t].edge_incidences.extend_from_slice(list);
            }
        }
        for list in vertices.values() {
            for &t in list {
                self.tiles[t].vertex_incidences.extend_from_slice(list);
            }
        }

        for (i, t) in self.tiles.iter_mut().enumerate() {
            // Remove duplicates and ourselves.
            t.edge_incidences = distinct_except(&t.edge_incidences, &[i]);
            t.vertex_incidences = distinct_except(&t.vertex_incidences, &[i]);

            // Only track vertex incidences that aren't also edge incidences.
            t.vertex_incidences = distinct_except(&t.vertex_incidences, &t.edge_incidences);
        }

        self.edge_incidences = edges;
        self.vertex_incidences = vertices;
    }

    pub fn count(&self) -> usize {
        self.tiles.len()
    }

    pub fn polygons(&self) -> impl Iterator<Item = &Polygon> {
        self.tiles.iter().map(|t| &t.drawn)
    }
}

/// LINQ's `Distinct().Except(...)`: distinct items in first-occurrence order, minus exclusions.
fn distinct_except(items: &[usize], except: &[usize]) -> Vec<usize> {
    let mut result = Vec::new();
    for &i in items {
        if !except.contains(&i) && !result.contains(&i) {
            result.push(i);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tolerance;

    #[test]
    fn platonic_tilings_are_complete() {
        // The face at infinity can't be recognized as already added (the identity Möbius map
        // turns infinity into NaN, exactly as in the original), so spherical tilings rely on
        // an exact tile limit.
        for (p, q, n) in [(3, 3, 4), (4, 3, 6), (3, 4, 8), (5, 3, 12), (3, 5, 20)] {
            let tiling = Tiling::generate(TilingConfig::spherical(p, q).unwrap());
            assert_eq!(tiling.count(), n, "{{{p},{q}}}");
            assert_eq!(tiling.tiles[0].edge_incidences.len(), p as usize, "{{{p},{q}}}");
        }
    }

    #[test]
    fn cube_incidences() {
        let tiling = Tiling::generate(TilingConfig::spherical(4, 3).unwrap());
        for t in tiling.tiles.iter().filter(|t| !t.has_points_projected_to_infinity()) {
            // Each cube face touches the 4 faces around it, and no others only at vertices.
            assert_eq!(t.edge_incidences.len(), 4);
            assert_eq!(t.vertex_incidences.len(), 0);
        }
    }

    #[test]
    fn hyperbolic_tiling() {
        let tiling = Tiling::generate(TilingConfig::new(7, 3, 500));
        // The limit is only checked between tiles, so we can overshoot by up to p-1.
        assert!((500..507).contains(&tiling.count()));
        let first = &tiling.tiles[0];
        assert_eq!(first.center(), Vector3D::ORIGIN);
        assert_eq!(first.edge_incidences.len(), 7);
        // In {p,3} the tiles around a vertex are all edge neighbors.
        assert_eq!(first.vertex_incidences.len(), 0);
        for t in &tiling.tiles {
            assert!(t.center().abs() < 1.0);
            // The stored isometry takes each tile back home.
            assert_eq!(t.isometry.apply(t.center()), Vector3D::ORIGIN);
        }
    }

    #[test]
    fn euclidean_tiling() {
        let tiling = Tiling::generate(TilingConfig::new(4, 4, 100));
        assert!((100..104).contains(&tiling.count()));
        let first = &tiling.tiles[0];
        assert_eq!(first.edge_incidences.len(), 4);
        assert_eq!(first.vertex_incidences.len(), 4);
        let side = tiling.tiles[first.edge_incidences[0]].center().abs();
        assert!(tolerance::equal(side, 2.0 * (1.0 / 3.0) * (PI / 4.0).cos()));
    }

    #[test]
    fn positions_match_tiling() {
        let config = TilingConfig::new(7, 3, 300);
        let positions = TilingPositions::build(&config);
        let tiling = Tiling::generate(config);
        let found = tiling.tiles.iter().filter(|t| positions.positions.contains(&t.center())).count();
        assert!(found > 100, "{found}");
    }
}
